### PR TITLE
chore: allow validation service to process subset of formats

### PR DESCRIPTION
**Pull request by danyalprout**
### Description
Some CL clients return malformed SSZ encoded blob sidecars, this causes the blob archive validation to fail -- even when the blob archive data is correct. This PR adds a flag which allows the operator to specify which formats to check.

### CODE REVIEW

**Review by fahimahmedx — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for fahimahmedx @ 2024-07-08 16:25:44 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by fahimahmedx — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for fahimahmedx @ 2024-07-10 16:33:07 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by fahimahmedx — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for fahimahmedx @ 2024-07-10 16:35:51 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by fahimahmedx — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for fahimahmedx @ 2024-07-10 19:52:53 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by fahimahmedx — APPROVED** [review]

**Pull request merged**
